config/routes.rb
Indsec::Application.routes.draw do
  resources :estimates

  resources :line_items
  resources :carts, only: [:show, :destroy]

  match 'store' => 'store#index', as: :store

  match 'cart' => 'carts#show', as: :current_cart

  resources :categories

  resources :products

end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  validates :name, :email, :address, :company, :phone, :location, presence: true
  has_many :line_items, autosave: true

  accepts_nested_attributes_for :line_items
  before_save :remove_cart_reference

  # Public: Adds the line_items  to the estimate
  #         from the cart and also removes the cart reference.
  #
  #     cart - Cart instance to migrate line_items from
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      line_items << item 
    end
  end

  private
  # Public: TODO FIX {should be inside of add_line_items_from_cart}
  #         Removes the reference to carts before saving an estimate.
  def remove_cart_reference
    self.line_items.update_all(cart_id: nil)
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estimates }
    end
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
    @estimate = Estimate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estimate }
    end
  end

  # GET /estimates/new
  # GET /estimates/new.json
  def new
    @estimate = Estimate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estimate }
    end
  end

  # GET /estimates/1/edit
  def edit
    @estimate = Estimate.find(params[:id])
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(estimate_params)
    @estimate.add_line_items_from_cart(current_cart)
    
    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: 'Estimate was successfully created.' }
        format.json { render json: @estimate, status: :created, location: @estimate }
      else
        format.html { render action: "new" }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    @estimate = Estimate.find(params[:id])

    respond_to do |format|
      if @estimate.update_attributes(estimate_params)
        format.html { redirect_to @estimate, notice: 'Estimate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate = Estimate.find(params[:id])
    @estimate.destroy

    respond_to do |format|
      format.html { redirect_to estimates_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def estimate_params
      params.require(:estimate).permit(:address, :company, :email, :location, :name, :phone)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.slim
h1 Please enter your information to proceed

= simple_form_for(@estimate) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :address
    = f.input :company
    = f.input :phone
    = f.input :location

  .form-actions
    = f.button :submit

app/views/estimates/edit.html.slim
h1 Editing estimate

== render 'form'

= link_to 'Show', @estimate
'|
= link_to 'Back', estimates_path

app/views/estimates/index.html.slim
h1 Listing estimates

table
  tr
    th Name
    th Email
    th Address
    th Company
    th Phone
    th Location
    th
    th
    th

  - @estimates.each do |estimate|
    tr
      td = estimate.name
      td = estimate.email
      td = estimate.address
      td = estimate.company
      td = estimate.phone
      td = estimate.location
      td = link_to 'Show', estimate
      td = link_to 'Edit', edit_estimate_path(estimate)
      td = link_to 'Destroy', estimate, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Estimate', new_estimate_path

app/views/estimates/new.html.slim
h1 New estimate

== render 'form'

= link_to 'Back', estimates_path

app/views/estimates/show.html.slim
p#notice = notice

p
  strong Name:
  = @estimate.name
p
  strong Email:
  = @estimate.email
p
  strong Address:
  = @estimate.address
p
  strong Company:
  = @estimate.company
p
  strong Phone:
  = @estimate.phone
p
  strong Location:
  = @estimate.location

= link_to 'Edit', edit_estimate_path(@estimate)
'|
= link_to 'Back', estimates_path